tasks:
  - name: Install Flutter
    init: |
      git clone https://github.com/flutter/flutter.git -b stable
      echo 'export PATH="$PATH:/workspace/$(basename $(pwd))/flutter/bin"' >> ~/.bashrc
      source ~/.bashrc
      flutter doctor
